project:
    name: dataexpert-airflow-dbt
    env:
    - PYTHONFAULTHANDLER
    - DATAEXPERT_AWS_ACCESS_KEY_ID
    - DATAEXPERT_AWS_SECRET_ACCESS_KEY
    - DATAEXPERT_POLYGON_API_KEY
    - DATAEXPERT_AWS_REGION
    - DATAEXPERT_AWS_DEFAULT_REGION
    - DATAEXPERT_S3_BUCKET_TABULAR
    - DATAEXPERT_TRINO_HOST
    - DATAEXPERT_TRINO_CATALOG
    - DATAEXPERT_TRINO_USER
    - DATAEXPERT_TRINO_PW
    - DATAEXPERT_DAG_OWNER
    - STUDENT_SCHEMA
    - PG_HOST
    - PG_DATABASE
    - PG_PORT
    - PG_USER
    - PG_PASSWORD
    - PG_SNAPSHOT_TABLE
    - PG_AUDIT_TABLE
    - SF_ACCOUNT
    - SF_USER
    - SF_ROLE
    - SF_WAREHOUSE
    - SF_DATABASE
    - SF_SCHEMA
    - SF_PRIVATE_KEY_PATH
    - SF_PRIVATE_KEY_PASSPHRASE
    - SF_PRIVATE_KEY_BASE64
    - SF_SNAPSHOT_TABLE
    - SF_AUDIT_TABLE

skip_parse: false
verbosity: debug
webserver:
    port: "8081"
postgres:
    port: "5431"
